name: CI

on:
  push:
    branches: [ "master" ]
jobs:
  build-react-native:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Build Artefact 
        run: cd android && chmod +x gradlew && ./gradlew assembleRelease

      - name: Run tests 
        run: npm run test

      - name: Installation ssh
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'random-value-text'

      - name: ajout Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Add folder apk
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} mkdir -p ./mobile/apk

      - name: run deploy
        run: rsync -avz ./android/app/build/outputs/apk/release/app-release.apk ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/mobile/

      - name: Rename folder
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'mv ~/mobile/apk ~/mobile/apk-$(date +%Y%m%d_%H%M%S)'